name: Github Action for LaTeX
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - uses: xu-cheng/latex-action@v2
        with:
          root_file: "main.tex"
      - name: move
        run: mkdir -p github_deploy && mv main.pdf github_deploy/
      - name: deploy on orphan branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github_deploy
          publish_branch: build
          force_orphan: true
