name: Github Action for LaTeX
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - uses: xu-cheng/latex-action@v2
        with:
          root_file: "main.tex"
      - name: Release PDF
        uses: softprops/action-gh-release@v1
        with:
          files: main.pdf
          tag_name: version
          name: Pdf degli appunti
